name: Deploy Versioned Pages
description: |
  Push documentation to the gh-pages branch with versioned URLs or clean up on deletion.

inputs:
  documentation_folder:
    description: "Path to the HTML files to deploy."
    required: true
  versions_file:
    description: "Path to the versions file on the gh-pages branch."
    default: "versions"

outputs:
  performed_action:
    description: "The action performed (deploy or delete)."
  target_folder:
    description: "The target folder for the documentation."

runs:
  using: "node20"
  main: "index.js"
